[package]
name = "todo_list"
version = "1.0.0"
authors = []

[addresses]
my_addr="0x42"
std="0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
